services:

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: portops-keycloak
    command: start-dev --import-realm 
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realm-portops.json:/opt/keycloak/data/import/realm-portops.json
    networks:
      - portops-net
  
  db-auth:
    image: postgres:16
    container_name: auth-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_ship
      PGDATA: /var/lib/postgresql/data/pg_data
    ports:
      - "3308:5432"
    volumes:
      - ./bases_datos/auth/data:/var/lib/postgresql/data
      - ./bases_datos/auth/init:/docker-entrypoint-initdb.d
    networks:
      - portops-net

networks:
  portops-net:
    driver: bridge