spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${HOST_DB}:${PORT_DB}/db_auth?sslmode=disable
    username: ${USER_DB}
    password: ${PASS_DB}
  
  flyway:
    url: ${FLYWAY_URL}
    user: ${FLYWAY_USER}
    password: ${FLYWAY_PASS}
    default-schema: ${FLYWAY_DEFAULT_SCHEMA}
    schemas: $FLYWAY_SCHEMAS}
    create-schemas: false


eureka:
  client:
    enabled: false

server:
  port: ${PORT:8004}
